version: '3.8'

services:
  api:
    build: .
    container_name: proxime-core-api
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: proxime-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
