version: '3.8'

services:
  zones-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zones-api
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - zones-mongo

  zones-mongo:
    image: mongo:6
    container_name: zones-mongo
    ports:
      - "27019:27017"
    volumes:
      - zones_mongo_data:/data/db

volumes:
  zones_mongo_data: